[custom.all.rhone-js]
type   = "local"
path   = "."
ipkg   = "rhone-js.ipkg"

[custom.all.rhone-js-docs]
type   = "local"
path   = "docs"
ipkg   = "docs.ipkg"

[custom.all.tailrec]
type   = "git"
url    = "https://github.com/stefan-hoeck/idris2-tailrec"
commit = "latest:main"
ipkg   = "tailrec.ipkg"
